fan_config:
  interval: 10000
  hysteresis:
    amount: 4
    only_way_down: true
  matrix:
    - [ 55, 10 ]
    - [ 60, 40 ]
    - [ 65, 100 ]
shutdown_script:
  location: "/home/admin/config.scripts/blitz.shutdown.sh"
  args: []
reboot_script:
  location: "/home/admin/config.scripts/blitz.shutdown.sh"
  args: ["reboot"]
